name: user_repository
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  common_repository:
    path: "../common_repository"
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  get_it: ^8.0.0
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  local_storage:
    path: "../local_storage"
  cloud_storage:
    path: "../cloud_storage"
  configuration:
    path: "../configuration"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner:
