name: notification
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  get_it: ^8.0.0
  injectable: ^2.4.2
  injectable_generator: ^2.6.1
  local_storage:
    path: "../local_storage"
  configuration:
    path: "../configuration"
  cloud_storage:
    path: "../cloud_storage"
  common_repository:
    path: "../common_repository"
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  firebase_messaging: ^15.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner:
