name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      # Upgrade win32 package
      - run: flutter pub upgrade win32

      # Get all the dependencies
      - run: flutter pub get

      # Update CocoaPods repository
      - run: pod repo update
        working-directory: ios

      # Build the iOS app in release mode without code signing
      - run: flutter build ios --release --no-codesign

      # Create Payload directory
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Move Runner.app to the Payload directory
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip the output to create an .ipa file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the IPA to GitHub release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
